name: Release Workflow

on:
  create:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # Assurez-vous que la version de Go correspond à celle de votre projet

    - name: Install Goreleaser
      run: |
        curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v1.14.0/goreleaser_Linux_x86_64.tar.gz | tar -xzv
        sudo mv goreleaser /usr/local/bin/goreleaser

    - name: Run Goreleaser
      run: goreleaser release --rm-dist --skip-publish

    - name: Build Docker Image
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}  # Extrait le tag de la release
        docker build -t yourusername/yourrepository:$IMAGE_TAG .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}  # Extrait le tag de la release
        docker push yourusername/yourrepository:$IMAGE_TAG
