name: GoReleaser

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
   goreleaser2-compilation:
      runs-on: ubuntu-latest
      steps:
        - name: Récupérer le code source
          uses: actions/checkout@v2
        - name: Release with goreleaser
          uses: goreleaser/goreleaser-action@v2
          with:
            args: release --skip-publish
          env:
              GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
              GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
          


          
   integration-into-the-release-artifacts:
      runs-on: ubuntu-latest
      steps:
        - name: Récupérer le code source
          uses: actions/checkout@v2
        - name: Publier les artefacts de version
          uses: actions/upload-artifact@v2
          with:
            name: release
            path: ./dist #le répertoire dans lequel les artefacts sont générés
        - name: Télécharger les artefacts de version
          uses: actions/download-artifact@v2
          with:
            name: release
