name: GoReleaser

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:

          
  goreleaser-compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Installer goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest

      - name: Compiler le projet avec goreleaser
        run: |
          goreleaser release --rm-dist
          
  integration-into-the-release-artifacts:
      runs-on: ubuntu-latest
      steps:
        - name: Télécharger les artefacts de version
          uses: actions/download-artifact@v2
          with:
            name: release

      # Étapes supplémentaires pour utiliser les artefacts de version
