name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  static-analysis-with-semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Analyse statique avec semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/golang"
          path: "."
          run: |
           docker run --rm -i semgrep/semgrep < ./super_calculator/Dockerfile2

  Dockerfile-analysis-with-hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Analyse Dockerfile avec hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile2

  superlint-execution-if-pull_request-evenement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Exécution de Super-Linter (uniquement sur pull_request)
        if: github.event_name == 'pull_request'
        uses: github/super-linter@v4
        with:
          validate_all_codebase: true
          default_branch: main
          debug: false
        
      - name: Sortie si l'événement n'est pas un pull_request #j'ai rajouté ce step pour automatiquement stopper le workflow après ses steps si l'evenement pull_request n'est pas enclenché
        if: github.event_name != 'pull_request'
        run: exit 0
