name: Plush Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  analyse-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Analyse statique avec semgrep
      uses: returntocorp/semgrep-action@v1

    - name: Analyse Dockerfile avec hadolint
      run: |
        docker run --rm -i hadolint/hadolint < ./super_calculator/Dockerfile2

    - name: Exécution de Super-Linter (uniquement sur pull_request)
      if: github.event_name == 'pull_request'
      uses: github/super-linter@v4
      with:
        validate_all_codebase: true
        default_branch: main
        debug: false
