name: Publication de l'image Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
    build-and-publish-image:
      runs-on: ubuntu-latest
      steps:
        - name: Récupérer le code source
          uses: actions/checkout@v2

        - name: Extraire la version depuis GITHUB_REF
          run: echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

        - name: Afficher la version extraite
          run: echo $DOCKER_TAG

        - name: Connectez-vous à Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Créer et publier l'image Docker
          uses: docker/build-push-action@v2
          with:
            context: ./super_calculator
            file: ./super_calculator/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/calculator7:${{ env.DOCKER_TAG }}


#
 #     - name: intall Go
  #      uses: actions/setup-go@v2
   #     with:
    #      go-version: ^1.16
     # - name: Install dependencies
      #  run: go mod tidy

      
      #- name: Release with goreleaser
       # uses: goreleaser/goreleaser-action@v2
        #with:
         # args: release --skip-publish
        #env:
         #   GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          #  GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
