name: Release workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  goreleaser-compilation:
    runs-on: ubuntu-latest
    steps:
      # - name: Installer goreleaser
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: release --rm-dist

        # Configurer Go
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        - name: Install Goreleaser
          uses: goreleaser/goreleaser-action@v6
        - name: Show GoReleaser version
          run: goreleaser -v
          
        # - name: Compiler le projet avec goreleaser
        #   run: |
        #     goreleaser release --rm-dist
        - name: Run Goreleaser
          uses: goreleaser/goreleaser-action@v4
          with:
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Obligatoire pour créer des artefacts et interagir avec GitHub

          
          
          
  integration-into-the-release-artifacts:
      runs-on: ubuntu-latest
      steps:
        - name: Télécharger les artefacts de version
          uses: actions/download-artifact@v2
          with:
            name: release



  build-and-publish-image:
      runs-on: ubuntu-latest
      steps:
        - name: Récupérer le code source
          uses: actions/checkout@v2

        - name: Extraire la version depuis GITHUB_REF
          run: echo "DOCKER_TAG=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

        - name: Afficher la version extraite
          run: echo $DOCKER_TAG

        - name: Connection à Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Créer et publier l'image Docker
          uses: docker/build-push-action@v2
          with:
            context: ./super_calculator
            file: ./super_calculator/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/macalco:${{ env.DOCKER_TAG }}


#
 #     - name: intall Go
  #      uses: actions/setup-go@v2
   #     with:
    #      go-version: ^1.16
     # - name: Install dependencies
      #  run: go mod tidy

      
      #- name: Release with goreleaser
       # uses: goreleaser/goreleaser-action@v2
        #with:
         # args: release --skip-publish
        #env:
         #   GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          #  GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}ion@v2
        #with:
         # args: release --skip-publish
        #env:
         #   GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          #  GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
