name: Bonus3 - Notify in Microsoft Teams
#comme bonus 2 j'ai crée ce workflow qui sera déclenché lorsqu'un nouveau commit sera effectué
#sur la branche main et envoyer une notification dans mon équipe Teams


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Team
        uses: microsoft/teams-set-status@v1
        with:
          endpoint: ${{ secrets.TEAMS_WEBHOOK_URL }} #j'ai crée un secret avec le webhook de mon équipe teams
          status: "success"
          message: |
            Code source mis à jour :
            Commit: ${{ github.sha }}
            Auteur: ${{ github.actor }}
            Date: ${{ github.event.head_commit.timestamp }}
