name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*' # Déclenchement sur des tags commençant par "v" suivi de numéros de version

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Remplacez par la version de Go que vous utilisez

      # Installer Goreleaser
      - name: Install Goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      # Exécuter Goreleaser
      - name: Run Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Nécessaire pour créer les artefacts
        run: goreleaser release --rm-dist

  docker:
    name: Build and Push Docker Image
    needs: release
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:$IMAGE_TAG .

      # Pusher l'image Docker
      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:$IMAGE_TAG
