name: Test Release Workflow

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: name: Release Workflow

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Install GoReleaser
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      # Run GoReleaser to build and release
      - name: Run GoReleaser
        run: goreleaser release --clean --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

