name: Test Release Workflow

on:
  push:
    tags:
      - "v*.*.*"  # Déclenche le workflow pour les tags de type vX.Y.Z
  workflow_dispatch:

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # # Verify that the tag is correct
      # - name: Verify Tag
      #   run: |
      #     if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v.*$ ]]; then
      #       echo "Error: This is not a valid tag."
      #       exit 1
      #     fi

      # Install and Run GoReleaser
      - name: Debug GITHUB_REF
        run: echo "GITHUB_REF: $GITHUB_REF"

      - name: Install and Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: release
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Verify tag name and Build Docker Image
      - name: Build Docker Image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Tag name: $TAG_NAME"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:$TAG_NAME .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:$TAG_NAME

